const mongoose = require('mongoose');

const CompanySchema = new mongoose.Schema({
  // Using the custom 'id' generated by the frontend (e.g., id-xxx)
  id: { type: String, required: true, unique: true },
  companyName: { type: String, required: true },
  adminName: { type: String, default: "" },
  email: { type: String, required: true, unique: true },
  password: { type: String, required: true },
  logoUrl: { type: String, default: "" },
  
  // Storing the arrays as Mixed types to easily accommodate the deep 
  // nesting of departments, managers, and team members without rigid schemas.
  leadership: { type: Array, default: [] },
  eas: { type: Array, default: [] },
  departments: { type: Array, default: [] }
}, { 
  timestamps: true 
});

module.exports = mongoose.model('Company', CompanySchema);